language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Zi4SeIOmAaqYznbMymlAaBhuKWGDvXZ5CQD8EmCs/kxHpemy03umu3YLHzHy4w7VSjudL2CqRgLDYow4b74ctA4xDPZdRA2PbnJxuPcjmaOB20MDsl377nh6qFOYs/2Zso/I5b3+XYXV5mMUt3UBc3iN3wMcAFA9sSRi8qotGDBHqvSJ+bm9KFMdfYDvcAPKXzhNrtWEFDaCKea56bh7WUJBXdBiIxEDdnkxuUT3Di0E76IQ2bznW5+o0g7kHS0YpWgc2PAx8ROLZHVIfw3VKdhdCdGpOcTGYW+DzPQ5AFF47vicgjrw6sI71I6E1ZmBa0IAQc750mfYkN57R3sPzNVU8jseIbtd0UZKIFFUadDZ7Tk70p54eRNIxaIVqzAVaBLmFSJpU6cb1UptNAt/1xhQfEz7rYrkWSk4x0mhePyqQC0eHpcKhLLOS3ctr6PTCn83pJkqpAeDr+l7rCLRX/rNjQbD5h2JCVzFtV0QvrSGeQ3WhvJSn72jw1SJ/06Y4Zs8fZvwi5/jmqBrdXpwo2kV68xRaCNpdEiFssR4RvZFFRcmV9btvwQ0JIzXXMzjwhFD3CJzpqznta4IZhXI1weZIyfhdJfd1DOgJaMHnMnI/OWxG9hvOzhPKFHDPCOjSUJQk5Q0NoKuYaXkDGeijskc8m1ZV/H9ilU8BpsVO1w=
  app: https://protected-hollows-64921.herokuapp.com/
  on:
    repo: michaelablackham/node-shopping-list-integration-tests
